name: Update Screenshot

on:
  push:
    branches:
      - main # Trigger when pushing to the main branch
  schedule:
    - cron: "0 5 * * *" # Run once every 24 hours at midnight EST

jobs:
  update-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Updated Screenshot
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl "https://api.apiflash.com/v1/urltoimage?access_key=${API_KEY}&wait_until=page_loaded&url=https://potentium.org" --output public/potentium-screenshot.png

      - name: Commit and Push Updated Image
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add public/potentium-screenshot.png
          git commit -m "Update screenshot for potentium.org" || echo "No changes to commit"
          git push
